name: Build
on: [push]
jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake qtbase5-dev qtbase5-dev-tools
      - name: Run Cmake
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Build library
        run: make -j