name: Build
on: [push]
jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            qtbase5-dev \
            qtbase5-dev-tools \
            qml-module-qtquick-controls \
            qml-module-qtquick-controls2
      - name: Run Cmake
        run: |
          mkdir build
          cd build
          cmake -DQNANO_WIDGETS=1 -DQNANO_QUICK=1 ..
      - name: Build library
        run: |
          cd build
          make -j
